spring.application.name=api-gateway

# Puerto donde API Gateway recibe solicitudes
server.port=8080

# Endpoint de Actuator para auditoría del Gateway
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,gateway