spring.application.name=microservicio-auth

# Puerto del Microservicio para Auth
server.port=8082

# Configuración R2DBC para MariaDB en Local
spring.r2dbc.url=r2dbc:mariadb://localhost:3306/chicheriabueno_auth_db
spring.r2dbc.username=root
spring.rdbc.password=chicheriabueno_auth_db

# Ejecución de scripts SQL al levantar el microservicio
spring.r2dbc.initialization-mode=always