spring.application.name=microservicio-inventario

# Puerto del Microservicio para Inventario
server.port=8082

# Configuración R2DBC para MariaDB en Local
spring.r2dbc.url=r2dbc:mariadb://localhost:3306/chicheriabueno_inventario_db
spring.rdbc.username=root
spring.rdbc.password=chicheriabueno_inventario_db

# Ejecución de scripts SQL al levantar el microservicio
spring.r2dbc.initialization-mode=always